spring:
    profiles: docker
eureka:
    instance:
        hostname: eureka-server
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Actuator settings, enables restart, shutdown URLs
# endpoints:
#     restart:
#         enabled: true
#     shutdown:
#         enabled: true

message: "Eureka server on Docker"